#!/usr/bin/env ruby

begin
  require 'rake'
rescue LoadError
  require 'rubygems'
  require 'rake'
end

$LOAD_PATH.unshift "../lib"
require "pwrake/branch/load"

Rake.application.run

#system "ps vx 1>&2"
