N=10

rule ".o" => ".c" do |t|
  #sh "sleep 0.1; echo --- #{t.name} $$ `hostname` `pwd` ---"
  sh "hostname >& /dev/null"
  #sh "env"
end

(1..N).map do |i|
  task "task#{i}.c"
end

obj = (1..N).map{|i| "task#{i}.o"}

task :default => obj do
  a=`ps vx`.split(/\n/)
  puts a.shift
  a.each{|l| puts l if /pwrake/=~l}
end
